### ISSUE TITLE
Create get endpoints on backend (Events)

### ISSUE THREAD

**Issue by Marcus-Aastum** [tiller-vgs/info-skjerm#20]
# Task Description
- Endpoints to return relevant events to frontend

# Linked User Story (-ies)
- #1

# Subtasks
- [x] Create an endpoint that returns an event by ID
- [x] Create an endpoint that returns today's events
- [x] Create an endpoint that returns this week's events
- [x] Create an endpoint that returns all events

**Comment by Marcus-Aastum** [comment]
This is NOT ready for a PR yet
